apiVersion: apps/v1
kind: Deployment
metadata:
  name: ingestor-deployment
spec:
  selector:
    matchLabels:
      app: edge
  replicas: 1
  template:
    metadata:
      labels:
        app: edge
    spec:
      containers:
      - name: api
        image: tracebloc/csv-ingestor:latest
        imagePullPolicy: Always
        volumeMounts:
          - name: shared-volume
            mountPath: "/data/shared"
        env:
        - name: EDGE_ENV
          value: "prod"
        - name: EDGE_USERNAME
          value: ""
        - name: EDGE_PASSWORD
          value: ""
        - name: EDGE_PVC
          value: "shared-pvc"
        - name: MYSQL_HOST
          value: "mysql"
        - name: MYSQL_USER
          value: "edgeuser"
        - name: MYSQL_PASSWORD
          value: ""
        - name: SRC_PATH
          value: "/data/shared/welds_inspections"
        - name: DEST_PATH
          value: "/data/shared/welds_inspections/txt/"
        - name: LABEL_FILE
          value: "/data/shared/welds_inspections/data.csv"
        - name: COMPANY
          value: "ABC_MC"
        - name: TABLE_NAME
          value: "table_name"
        - name: TEXT_INTENT
          value: "train"
      imagePullSecrets:
      - name: regcred
      volumes:
        - name: shared-volume
          persistentVolumeClaim:
            claimName: shared-pvc
      restartPolicy: Always
