apiVersion: batch/v1
kind: Job
metadata:
  name: ingestor-job
spec:
  template:
    spec:
      containers:
      - name: api
        image: company/your_image_name:latest
        imagePullPolicy: Always
        volumeMounts:
          - name: shared-volume
            mountPath: "/data/shared"
        env:
        - name: CLIENT_ENV
          value: "prod"
        - name: CLIENT_ID
          value: "edgeuser"
        - name: CLIENT_PASSWORD
          value: ""
        - name: CLIENT_PVC
          value: "shared-pvc"
        - name: MYSQL_HOST
          value: "mysql"
        - name: SRC_PATH
          value: "/data/shared/"
        - name: DEST_PATH
          value: "/data/shared/"
        - name: LABEL_FILE
          value: "/data/shared/sample.csv"
        - name: COMPANY
          value: "ABC_MC"
        - name: TABLE_NAME
          value: "table_name"
        - name: TITLE
          value: "dataset title" # Optional: provide a title for the dataset
      imagePullSecrets:
      - name: regcred
      volumes:
        - name: shared-volume
          persistentVolumeClaim:
            claimName: shared-pvc
      restartPolicy: Never
