apiVersion: batch/v1
kind: Job
metadata:
  name: ingestor-job-test-data # train/test switch
  namespace: <CHANGE_ME NAMESPACE>
spec:
  template:
    spec:
      containers:
      - name: api
        image: tracebloc/<CHANGE_ME TAG_NAME>-tabular-regression-sample-ingestor-test-data:latest # train/test switch
        imagePullPolicy: Always
        volumeMounts:
          - name: shared-volume
            mountPath: "/data/shared/" # Storage path within the client cluster (not the ingestor path). The data ingestor will copy all images and text files to that location.
        env:
        # Client credentials 
        - name: CLIENT_ENV
          value: "dev"
        - name: CLIENT_ID
          value: "<CHANGE_ME>"
        - name: CLIENT_PASSWORD
          value: "<CHANGE_ME>"
        - name: CLIENT_PVC
          value: "client-pvc"
        - name: MYSQL_HOST
          value: "mysql-client"
        - name: SRC_PATH
          value: "/data/shared" # Source folder path whithin the data ingestor
        - name: LABEL_FILE
          value: "/data/shared/tabular_regression_sample_in_csv_format.csv" # train/test switch
        - name: TABLE_NAME
          value: "tabular_regression_sample_test" # train/test switch
        - name: TITLE
          value: "Tabular Regression Sample Test Data" # Optional: provide a title for the dataset
        - name: LOG_LEVEL
          value: "WARNING"
      imagePullSecrets:
      - name: regcred
      nodeSelector:
        type: system
      volumes:
        - name: shared-volume
          persistentVolumeClaim:
            claimName: client-pvc # value has to match the shared data PVC name in the client values.yaml
      restartPolicy: Never
