apiVersion: batch/v1
kind: Job
metadata:
  name: ingestor-job
  namespace: <NAMESPACE>
spec:
  template:
    spec:
      containers:
      - name: api
        image: <YOUR_DOCKER_USER>/<YOUR_IMAGE_NAME>:latest
        imagePullPolicy: Always
        volumeMounts:
          - name: shared-volume
            mountPath: "/data/shared-data" # Storage path within the client cluster (not the ingestor path). The data ingestor will copy all images and text files to that location.
        env:
        - name: CLIENT_ENV
          value: "prod"
        - name: CLIENT_ID
          value: <YOUR_CLIENT_ID>
        - name: CLIENT_PASSWORD
          value: <YOUR_CLIENT_PASSWORD>
        - name: CLIENT_PVC # Source folder path whithin the data ingestor
          value: "shared-pvc"
        - name: MYSQL_HOST # Name of the MYSQL_HOST in has to match the mysql deployment name in the client values.yaml.
          value: "mysql"
        - name: SRC_PATH
          value: "/data" # Source folder path whithin the data ingestor
        - name: LABEL_FILE
          value: <PATH_TO_LOCAL_DATASET_FILE>  # Example: "/data/examples.csv"
        - name: COMPANY
          value: <YOUR_COMPANY_OR_ORGANISATION_NAME>
        - name: TABLE_NAME
          value: <UNIQUE_TABLE_NAME> # provide a unique table name
        - name: TITLE
          value: <DATASET_TITLE> # Optional: provide a title for the dataset
      imagePullSecrets:
      - name: regcred
      volumes:
        - name: shared-volume
          persistentVolumeClaim:
            claimName: shared-pvc # Source folder path whithin the data ingestor
      restartPolicy: Never
