apiVersion: batch/v1
kind: Job
metadata:
  name: ingestor-job
  namespace: <NAMESPACE>
spec:
  template:
    spec:
      containers:
      - name: api
        image: <YOUR_DOCKER_USER>/<YOUR_IMAGE_NAME>:latest
        imagePullPolicy: Always
        volumeMounts:
          - name: shared-volume
            mountPath: "/data/shared"
        env:
        - name: CLIENT_ENV
          value: "prod"
        - name: CLIENT_ID
          value: "edgeuser"
        - name: CLIENT_PASSWORD
          value: ""
        - name: CLIENT_PVC
          value: "shared-pvc-16"
        - name: MYSQL_HOST
          value: "mysql-16"
        - name: SRC_PATH
          value: "/data/shared/"
        - name: LABEL_FILE
          value: "/data/shared/sample.csv" # path to local csv or json file
        - name: COMPANY
          value: "ABC_MC"
        - name: TABLE_NAME
          value: "table_name" # unique table name
        - name: TITLE
          value: "dataset title" # Optional: provide a title for the dataset
      imagePullSecrets:
      - name: regcred
      volumes:
        - name: shared-volume
          persistentVolumeClaim:
            claimName: shared-pvc-16
      restartPolicy: Never
